### ISSUE TITLE
Simplify usage

### ISSUE THREAD

**Issue by felixfbecker** [sushantdhiman/sequelize-benchmark#2]
Can we change this so that `npm link` is not required, but instead you just install this from NPM as a global module, then cd into the sequelize dir and run `sequelize-benchmark` as a CLI?

**Comment by sushantdhiman** [comment]
Yeah, thats a good idea. I'll see what can be done :)

**Comment by felixfbecker** [comment]
I think you just need to do `require(process.cwd())`

**Comment by sushantdhiman** [comment]
Added this feature in [v0.4.0](https://github.com/sushantdhiman/sequelize-benchmark/releases/tag/v0.4.0), Thanks for this suggestion @felixfbecker , Really good idea :)
