### ISSUE TITLE
error “Got a packet bigger than 'max_allowed_packet' bytes” on MySQL bulkCreate test

### ISSUE THREAD

**Issue by natesilva** [sushantdhiman/sequelize-benchmark#23]
Hi! I’m having trouble getting this to run. I’m getting this error:

>  $ DIALECT=mysql ./node_modules/.bin/env-cmd ./test/config/.docker.env sequelize-benchmark
>   sequelize:perf Using mysql DIALECT. +0ms
>   sequelize:perf Env ready +1s
>   sequelize:perf Starting findAll +8s
>   sequelize:perf finding 1500 rows x 8.20 ops/sec ±2.62% (43 runs sampled) (mean 0.121919s) +6s
>   sequelize:perf finding(raw) 1500 rows x 11.30 ops/sec ±1.09% (55 runs sampled) (mean 0.088529s) +6s
>   sequelize:perf finding(plain) 1500 rows x 7.86 ops/sec ±1.80% (41 runs sampled) (mean 0.127250s) +6s
>   sequelize:perf finding 1500 rows with join x 3.53 ops/sec ±2.87% (22 runs sampled) (mean 0.283684s) +7s
>   sequelize:perf finding 10 rows x 106 ops/sec ±1.33% (77 runs sampled) (mean 0.009467s) +6s
>   sequelize:perf finding(raw) 10 rows x 114 ops/sec ±1.45% (74 runs sampled) (mean 0.008761s) +6s
>   sequelize:perf finding(plain) 10 rows x 111 ops/sec ±1.54% (72 runs sampled) (mean 0.009031s) +6s
>   sequelize:perf finding 10 rows with join x 86.81 ops/sec ±1.29% (77 runs sampled) (mean 0.011519s) +6s
>   sequelize:perf Starting bulkCreate +972ms
> Unhandled rejection SequelizeDatabaseError: Got a packet bigger than 'max_allowed_packet' bytes
>     at Query.formatError (/Users/nate/code/sequelize/lib/dialects/mysql/query.js:220:16)
>     at Query.connection.query [as onResult] (/Users/nate/code/sequelize/lib/dialects/mysql/query.js:55:23)
>     at Query.Command.execute (/Users/nate/code/sequelize/node_modules/mysql2/lib/commands/command.js:31:12)
>     at Connection.handlePacket (/Users/nate/code/sequelize/node_modules/mysql2/lib/connection.js:417:28)
>     at PacketParser.onPacket (/Users/nate/code/sequelize/node_modules/mysql2/lib/connection.js:93:16)
>     at PacketParser.executeStart (/Users/nate/code/sequelize/node_modules/mysql2/lib/packet_parser.js:73:14)
>     at Socket.<anonymous> (/Users/nate/code/sequelize/node_modules/mysql2/lib/connection.js:101:29)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:548:20)

My config is:

* Latest Sequelize master branch @ 15f6ad9
* sequelize-benchmark 1.0.0 from npm
* MySQL server is the Docker config that comes with Sequelize (`docker-compose up mysql-57`)

I’ve run this on my Mac and from a Docker Ubuntu VM.

I’ve also tried:

* Using the master branch of sequelize-benchmark @ bf3a1e2
* Using the v4.0.0-2 branch of Sequelize

All with the same results.

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sushantdhiman/sequelize-benchmark/commit/fdc0239436e3197e6d289c0e68c767a42cc05229

**Comment by natesilva** [comment]
Thank you! I see you ran the benchmark against my other PR too.
